---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install git,tree and wget by using same task
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget